### ISSUE TITLE
Post Shmoocon 2017 slides?

### ISSUE THREAD

**Issue by TheBigS** [pbiernat/ripr#2]
Saw your talk at Shmoocon 2017, would be great to have the slides as reference, can you post them in a `docs/` folder in this repo, or somewhere else on the web and link it in the `README.md`. Thanks!

**Comment by pbiernat** [comment]
Probably should have done that originally :p. Added shmoocon slides in 902d06978f3b045cd019b96dbe6a0a3c12df3a82
