### ISSUE TITLE
Update Plugin for Plugin Manager 2.0

### ISSUE THREAD

**Issue by plafosse** [pbiernat/ripr#21]
With the introduction of the Binary Ninja Plugin Manager 2.0 we will be releasing a installation UI for all plugins in the community repository. Please check https://binary.ninja/2019/07/04/plugin-manager-2.0.html for the latest information about how to submit your plugin. If you no longer want your plugin in the repository please disregard this issue

**Comment by psifertex** [comment]
*ping* Just checking to see if you have plans to update for the new plugin manager. Would love to make this more discoverable.

**Comment by psifertex** [comment]
This can be closed!
