### ISSUE TITLE
conform to plugin.json format?

### ISSUE THREAD

**Issue by psifertex** [pbiernat/ripr#6]
Binary Ninja now has a plugin repository and an installer (with a gui installer coming at some point). Do you mind updating the plugin with a `plugin.json` file? (As described https://github.com/Vector35/community-plugins#contributing-plugins )

**Comment by pbiernat** [comment]
Yea, I'll definitely do that.

 Is it enough to stick a `plugin.json` into the ripr folder, or should things to be restructured so the "repo root" can be cloned into the binja plugin folder and used immediately? (With `plugin.json` being in the "root")

**Comment by zglozman** [comment]
In the meantime how do i get ripr to work?
